[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"  # Pasta das funçoes serverless

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200