[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/render"
  to = "200"
  status = 200
  force = true